version: 2.1

orbs:
  android: circleci/android@2.0

jobs:

  build-and-unit-test:
    executor:
      name: android/android-machine

    parameters:
      build-type:
        default: debug
        type: enum
        enum:
          - debug
          - staging
          - release
    environment:
      BUILD_TYPE: << parameters.build-type >>

    steps:
      - run:
          name: Buildtype
          command: |
            if [[ "$BUILD_TYPE" == "release" ]];then
              echo "This is release"

            else
              if [[ "$BUILD_TYPE" == "staging" ]];then
                echo "This is staging"
              else
                echo "This is debug"
              fi
            fi

workflows:

  build-and-test-main:
    jobs:
      - build-and-unit-test:
          build-type: release
          filters:
            branches:
              only: main
